### PR TITLE
Make module (almost) thread-safe.

### PR DESCRIPTION
**Pull request by samuelvarley**
The only area with a remaining threading issue is the fallback method in get_random_vector().

### CODE REVIEW

**Comment by alandekok** [comment]
That's nice, but why does the module have to be thread-safe?  99.999% of applications use PAM once, to authenticate one user, in a thread-safe way.

There are very few applications like FreeRADIUS which use PAM to authentication to authenticate multiple users.

**Comment by samuelvarley** [comment]
Hi Alan,

I am working on one of the rare applications for which it does matter. For performance reasons, we authenticate multiple users in parallel. Different requests may get sent to different groups of RADIUS servers. If one group is unreachable then we don't want requests destined for a different RADIUS group to sit in a queue while requests time out.

Although most use cases do not require thread safety, making the module thread safe should not cause any regression for them. But making the module thread safe gives options to others who could benefit from these changes.

**Comment by mweissen13** [comment]
I second the thread-safety. At least for the parameter which specifies the config file.
I can successfully reproduce problems when pam_radius_auth is used as PAM plugin for mariadb: sometimes the authentication will fail with 'No such file or directory' because the module will tries to open /etc/raddb/server instead of the file configured via the conf= parameter. I've worked around the issue by placing a symlink at /etc/raddb/server to the actual file used, which may not always be a good solution (think different config's for different services).

**Comment by alandekok** [comment]
OK, the patch looks pretty good.  I could have some minor nits over formatting, etc. but it's all fine.

Anyone willing to test it and double-check it?

**Comment by alandekok** [comment]
Please confirm that it works, and I'll pull the patch over.

**Comment by mweissen13** [comment]
Hm, commit e2af858a6e8de859af6ca4198fd60ea4405df3d8 doesn't apply against version 1.4.0. I can't see why tough.

**Comment by mweissen13** [comment]
Nevermind, patch 5a8d63de11de78854d83a4218c79cb203e6b5ea0 needs to reversed first. Applies and compiles cleanly now. Will report back after testing.

**Comment by mweissen13** [comment]
I just saw the patch was recently merged.
This is just a quick update: i've been running it now for more than a week in production without any issues. 5,016 k successful authentications so far.

**Comment by alandekok** [comment]
Thanks.  I also put a few other fixes in at the same time.  I'll push out a new release soon.

**Pull request merged**
