### PR TITLE
Honor prompt attribute during challenge

### PR DESCRIPTION
**Pull request by scootersmk**
Fix for issue #22

While I would personally prefer this option to be on by default, I figured making it configurable and off by default would make current users of this module happier.

### CODE REVIEW

**Comment by scootersmk** [comment]
Any chance of getting this merged?

**Comment by alandekok** [comment]
I'll take a look later today.  It looks good over all.

**Comment by scootersmk** [comment]
When trying to resolve a merge conflict this branch got messed up due to a combination of github UI and user error, so i'm going to create a new branch and MR that is cleaner looking.

**Comment by scootersmk** [comment]
See #38

**Pull request closed without merging**
